{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    gardener.cloud/purpose: machineclass
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
  kubeconfig: {{ $machineClass.secret.kubeconfig | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: "{{ $.Release.Namespace }}"
providerSpec:
{{- if $machineClass.storageClassName }}
  storageClassName: "{{ $machineClass.storageClassName }}"
{{ end }}
{{- if $machineClass.pvcSize }}
  pvcSize: "{{ $machineClass.pvcSize }}"
{{ end }}
{{- if $machineClass.sourceURL }}
  sourceURL: "{{ $machineClass.sourceURL }}"
{{ end }}
{{- if $machineClass.cpus }}
  cpus: "{{ $machineClass.cpus }}"
{{ end }}
{{- if $machineClass.memory }}
  memory: "{{ $machineClass.memory }}"
{{ end }}
  sshKeys:
{{ toYaml $machineClass.sshKeys | indent 4 }}
{{- if $machineClass.networkNames }}
  networkNames:
{{ toYaml $machineClass.networkNames | indent 4 }}
{{- end }}
secretRef:
  name: "{{ $machineClass.name }}"
  namespace: "{{ $.Release.Namespace }}"
provider: kubevirtdriver//127.0.0.1:8080
{{- end }}
